#!/usr/bin/bash
#PBS -N Class1
#PBS -l walltime=03:00:00
#PBS -l mem=64g
#PBS -l nodes=1:ppn=1

python3 main.py --gene_id ./testdata/gene_ids.txt \
    --Tm 60.0 --min_primer_size 18 --max_primer_size 20\
    --gtf_file /data/gent/vo/000/gvo00027/resources/Ensembl_transcriptomes/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.109.chrIS_spikes_45S.gtf \
    --transcriptome /data/gent/vo/000/gvo00027/resources/Ensembl_transcriptomes/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.109.chrIS_spikes_45S.fa \
    --btw_index /data/gent/vo/000/gvo00027/resources/Bowtie2_index/Homo_sapiens/Transcriptome_Homo_sapiens.GRCh38.109.chrIS_spikes_45S/bowtie2_index \
    --dist 400 --repeat_lib ./rep_lib/humrep_and_simple.txt --out_dir ./outputs/Class1_filt

samtools view -F 0x04 -c RNA032790_S1_Aligned.sortedByCoord.out.bam

No_dedup = 5515298
dedup_nosorted = 2422749
dedup_sorted = 2422749