#!/usr/bin/bash
#PBS -N Class1_InformedCoverage
#PBS -l walltime=03:00:00
#PBS -l mem=64g
#PBS -l nodes=1:ppn=1


python3 main_informed.py --gene_id ./testdata/gene_ids.txt \
    --bam_file /user/gent/446/vsc44685/ScratchVO_dir/NSQ2K_126_test/3_Star/Merged_S7_S12.bam \
    --Tm 60.0 \
    --min_primer_size 18 \
    --max_primer_size 20 \
    --min_product_size 25 \
    --max_product_size 80 \
    --gtf_file /data/gent/vo/000/gvo00027/resources/Ensembl_transcriptomes/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.109.chrIS_spikes_45S.gtf \
    --blastDB /data/gent/vo/000/gvo00027/resources/Blast_databases/RefSeq_select/human_refseq_db \
    --ref_genome /data/gent/vo/000/gvo00027/resources/Ensembl_genomes/Homo_sapiens/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.chrIS_spikes_45S.fa \
    --window 60 \
    --cov_thresh 5 \
    --repeat_lib /user/gent/446/vsc44685/ScratchVO_dir/NSQ2K_126_test/primer_design/rep_lib/humrep_and_simple.txt \
    --out_dir ./Class1_cov1 
    
